import '../data_sources/remote/ai_api.dart';
import '../data_sources/remote/supabase_api.dart';
import '../data_sources/local/local_storage.dart';
import '../models/correction_request.dart';
import '../models/chat_session_model.dart';

class CorrectionRepository {
  final AIApi _aiApi;
  final SupabaseApi _supabaseApi;
  final AppLocalStorage _localStorage;

  CorrectionRepository(
    this._aiApi,
    this._supabaseApi,
    this._localStorage,
  );

  /// Correct text using AI
  Future<String> correctText(CorrectionRequest request) async {
    final response = await _aiApi.correctText(request);
    return response.corrected;
  }

  /// Save chat session to database and local storage
  Future<void> saveChatSession({
    required String userId,
    required String correctedText,
    required String inputText,
    required String language,
    required String model,
  }) async {
    final session = ChatSessionModel(
      id: '', // Will be generated by database
      userId: userId,
      correctedText: correctedText,
      inputText: inputText,
      language: language,
      model: model,
    );

    // Save to database if user is authenticated
    if (userId.isNotEmpty) {
      try {
        await _supabaseApi.saveChatSession(session);
      } catch (e) {
        // If database save fails, still save locally
        print('Failed to save to database: $e');
      }
    }

    // Always save to local storage
    final chatHistory = _localStorage.getChatHistory();
    chatHistory.insert(0, {
      'id': DateTime.now().millisecondsSinceEpoch.toString(),
      'correctedText': correctedText,
      'inputText': inputText,
      'language': language,
      'model': model,
      'createdAt': DateTime.now().toIso8601String(),
    });
    
    // Keep only last 100 items
    if (chatHistory.length > 100) {
      chatHistory.removeRange(100, chatHistory.length);
    }
    
    await _localStorage.saveChatHistory(chatHistory);
  }

  /// Get chat history
  Future<List<ChatSessionModel>> getChatHistory(String? userId) async {
    if (userId != null && userId.isNotEmpty) {
      try {
        // Get from database if authenticated
        return await _supabaseApi.getChatSessions(userId);
      } catch (e) {
        print('Failed to fetch from database: $e');
      }
    }

    // Fall back to local storage
    final localHistory = _localStorage.getChatHistory();
    return localHistory
        .map((json) => ChatSessionModel(
              id: json['id'] ?? '',
              userId: userId ?? '',
              correctedText: json['correctedText'] ?? '',
              inputText: json['inputText'] ?? '',
              language: json['language'] ?? 'english',
              model: json['model'] ?? 'gpt-3.5-turbo',
              createdAt: json['createdAt'] != null
                  ? DateTime.parse(json['createdAt'])
                  : null,
            ))
        .toList();
  }
}

